### ISSUE TITLE
extend undefined

### ISSUE THREAD

**Issue by RobTech1** [kyranet/Sneyra#157]
I get this error:
C:\Users\roberob\Downloads\Sneyra-master\node_modules\klasa\src\lib\extensions\KlasaGuild.js:3
module.exports = Structures.extend('Guild', Guild => {
                            ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (C:\Users\roberob\Downloads\Sneyra-master\node_modules\klasa\src\lib\extensions\KlasaGuild.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\roberob\Downloads\Sneyra-master\node_modules\klasa\src\index.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:738:30)

**Comment by kyranet** [comment]
You didn't download the dependencies correctly, Sneyra depends on discord.js master.
