### ISSUE TITLE
Is this maintained ?

### ISSUE THREAD

**Issue by bernzJ** [kyranet/Sneyra#4]
Hi, title, if so I get: 
```
TypeError: klasa.Client.defaultPermissionLevels.add is not a function
    at Object.<anonymous> (d:\Github\Sneyra\index.js:6:6)
    at Module._compile (module.js:632:14)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
at [this line](https://github.com/kyranet/Sneyra/blob/master/index.js#L5).

Meanwhile I will be reading klasa's docs, also very clean code.

**Comment by bernzJ** [comment]
Solved by upgrading klasa version via npm: [npm i klasa](https://www.npmjs.com/package/klasa)

**Comment by kyranet** [comment]
Yes, it's maintained and actively used, Sneyra uses klasa/master (check `package.json`). But I have to update it for the latest breaking changes in klasa/master.
