### ISSUE TITLE
TypeError: Client.defaultPermissionLevels.add is not a function

### ISSUE THREAD

**Issue by dpprdev** [kyranet/Sneyra#93]
```js
/app/src/Sneyra.js:9

	.add(5, (msg) => msg.member && msg.guild.settings.dj && msg.member.roles.has(msg.guild.settings.dj), { fetch: true })

	 ^


TypeError: Client.defaultPermissionLevels.add is not a function

at Object.<anonymous> (/app/src/Sneyra.js:9:3)

    at Module._compile (internal/modules/cjs/loader.js:689:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

    at Module.load (internal/modules/cjs/loader.js:599:32)

    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

    at startup (internal/bootstrap/node.js:283:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```
^ i recieve this. I guess it's a bug.

**Comment by kyranet** [comment]
Are you sure you're installing Sneyra correctly? It requires klasa master.

**Comment by dpprdev** [comment]
@kyranet Well, when i tried installing klasa master, it throwed that deafultLevelPermissions is undefined.

**Comment by kyranet** [comment]
Except it is... can you inspect that?

![image](https://user-images.githubusercontent.com/24852502/53700021-7a9b0000-3dee-11e9-8e43-58cdfaa4c439.png)

**Comment by dpprdev** [comment]
Appears that NPM didn't install klasa master. Everything works now. Thanks.

**Comment by dpprdev** [comment]
Closing.
